Middle section and about me section designed like Figma template
lexoxo/Portfolio-setup-and-mobile-version-skeleton pull request #2
Opened 2022-02-11 11:18 UTC by lexoxo

This branch brings some styles to design the portfolio like the third template of Figma templates

2022-02-11 12:14 UTC, ReshyResh requested changes
# Hi @lexoxo , 

### Good job so far, your portfolio looks great!
  - ✔ Correct use of Flexbox and Grid to lay out elements.
  - ✔ Descriptive commit messages and professional looking repository.
  - ✔ No linter errors.


#### There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Please check the comments under the review._


Cheers and Happy coding! 👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 12:14 UTC, ReshyResh commented on index.html
> +            <p class="work-description">Multi-Post Stories Gain+Glory</p>
- [ ] Please make sure the title of each work card title uses an `hx` tag, for example `h2`.

2022-02-11 12:14 UTC, ReshyResh commented on index.html
> +    <h1 class="about-me">About me</h1>
- [ ] For both semantic and SEO purposes, you should always avoid having multiple `h1` tags in a single page, please make sure to change this to another tag and style it accordingly.

2022-02-11 12:14 UTC, ReshyResh commented on index.html
> +<div class="resume-button">Get My Resume</div>
- [ ] I suggest you change this to a `button` tag, as this is its function. Good job on implementing the interactions!

2022-02-11 12:14 UTC, ReshyResh commented on index.html
> +    <div class="under-bar"></div>
- [ ] Please make sure to add a bit more spacing to those elements as they're currently overlapping each other.


![](https://i.imgur.com/0YRMz4I.png)

2022-02-11 12:56 UTC, lexoxo commented on index.html
> +    <div class="under-bar"></div>
Thanks for the feedback

2022-02-11 12:58 UTC, ReshyResh approved these changes
# Hi again @lexoxo , 

### Good job addressing the changes requested previously!
#### Your project is complete!  There is nothing else to say other than... it's time to merge it!
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

----

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2022-02-11 13:00 UTC, merged

2022-02-15 09:07 UTC, EzekielUtshudi commented on index.html
> +            <p class="work-description">Multi-Post Stories Gain+Glory</p>
Your work is well structured but lease next time have more descriptive comments to help others understand your codes.