Portfolio: updating for desktop view responsiveness
lexoxo/Portfolio-setup-and-mobile-version-skeleton pull request #5
Opened 2022-02-17 18:24 UTC by lexoxo

# The aim is to make it responsive 💯

2022-02-17 19:50 UTC, mahbubul14 requested changes
# Required Changes ♻️

Hi @lexoxo ,

Good job so far! :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

### Mandatory Requirements:

- [ ] Check the comments under the review. :arrow_down: 

###  To Highlights
:heavy_check_mark: No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Clean code

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also reach me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-02-17 19:50 UTC, mahbubul14 commented on styles.css
> +  }
- [ ] In the required desktop version, currently your "My Recent Works" section does not match with the Figma design. Add some spaces on the left & right sides. :writing_hand: 

> - **Your implementation:**

![m3](https://user-images.githubusercontent.com/70483835/154554910-01f0e901-e358-4bb3-bb5e-4c6a15da4627.png)

> - **Figma design:**

![m1](https://user-images.githubusercontent.com/70483835/154554669-8ec4a3ac-c1aa-4dcf-a392-730ca65a418e.png)

2022-02-17 19:50 UTC, mahbubul14 commented on index.html
> +        </p>
- [ ] For the required desktop version, the text doesn't match your Figma design. The text should be fit besides the contact form. Kindly work on that.  :writing_hand: 

- **Your implementation:**
![c1](https://user-images.githubusercontent.com/70483835/154556429-af131fe4-088d-4daf-97f8-5ac49aa09038.png)
- **Figma design:**
![c2](https://user-images.githubusercontent.com/70483835/154556608-d73322df-e8b9-4f4e-9ffb-6467d6f7aee5.png)

2022-02-17 19:50 UTC, mahbubul14 commented on styles.css
> +  }
- [ ] In the required desktop version, currently this section does not match with the Figma design. Add some spaces on the left & right sides. :writing_hand: 

> - **Your Implemantation:**
![s1](https://user-images.githubusercontent.com/70483835/154558433-63ea5a08-4ac3-472b-a8d9-41bd831ff6de.png)

> - **Figma Design:**
![s2](https://user-images.githubusercontent.com/70483835/154558451-40d2c5ac-2233-4172-b633-eab014234246.png)

2022-02-17 20:53 UTC, lexoxo commented on index.html
> +        </p>
@mahbubul14 Thanks 👍  for the feedback. But i see on the screenshot that you compare 1080px width with figma template. Figma template is 1440px width.

2022-02-18 00:56 UTC, mahbubul14 commented on index.html
> +        </p>
@lexoxo In your project requirements, you can check bullet point 3. It is said, "Use media queries in your CSS file to make your desktop version look like the template you selected (let's assume that the desktop width should be in 992px - 1100px range)." What I suggested to you, is not fitted with that range. :+1: 

![c](https://user-images.githubusercontent.com/70483835/154596753-cbfa61e8-84fd-4aa9-9f64-947e7df08fe2.png)

2022-02-18 06:45 UTC, lexoxo commented on index.html
> +        </p>
@mahbubul14 Yes i see. But it will not be possible to stick to it. You can look the width of Figma templates, it is1440 px

2022-02-18 10:55 UTC, Whoistolu commented on styles.css
> +  }
- [ ] I see that you have implemented most of the changes required except the little green line right under "My Recent Works", kindly remove it .

2022-02-18 10:56 UTC, Whoistolu commented on index.html
> +        </p>
All good now 👍🏽

2022-02-18 11:00 UTC, Whoistolu approved these changes
### Hi @lexoxo,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

- [ ]  _Check the inline comments under the review for sections to improve._

- [ ] [OPTIONAL] Kindly ensure you always add a description to your Pull Request, it enables visitors to have a proper idea of the changes implemented.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 11:40 UTC, merged

2022-02-18 15:53 UTC, Whoistolu commented
> @Whoistolu Thanks for the feedback and the review

You are welcome @lexoxo